GO := go

generate:
	go generate ./...

build: generate
	 go build ./...

unit-test:
	go test -race -mod=readonly ./...

lint:
	golangci-lint run ./...
	go fmt ./...

test:
	go test -race -mod=readonly -race -coverpkg=./... -covermode=atomic -coverprofile=coverage.out.tmp ./...
	cat coverage.out.tmp | grep -v "/mock_" > coverage.txt #IGNORE MOCKS
	go tool cover -html=coverage.txt -o coverage.html
